### ISSUE TITLE
Support Llama3

### ISSUE THREAD

**Issue by CiaoHe** [belladoreai/llama-tokenizer-js#15]
Thx for your awesome work! I always use this app for demonstration.
Till 2024/4/19, llama-3 is released with 128k tokens, would you plan to support the new version?

Glad to hear the latest updates!

**Comment by belladoreai** [comment]
Yes. I am currently working on LLaMA 3 support. There's a lot of changes so I will make a new repo for it.

**Comment by belladoreai** [comment]
Hmmh, looks like it requires a lot more work than I expected. Can anybody assist with this?

I'm having trouble understanding the following aspects of LLaMA 3 tokenizer:
- According to the `tokenizer.json` file, the `post_processor` has `add_prefix_space` set to `true`, but when the tokenizer is used via transformers library, it doesn't appear to add a prefix space. Is it supposed to add a prefix space or not? If not, why is this flag set to `true`? If yes, why doesn't it work in transformers?
- Unlike the original LLaMA tokenizer, this one has 2 pretokenizers. I'm trying to understand how I'm supposed to apply these pretokenizers:
    - The first one looks like it's supposed to split the input according to this complicated regex that doesn't parse correctly in JavaScript: `(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\\r\\n\\p{L}\\p{N}]?\\p{L}+|\\p{N}{1,3}| ?[^\\s\\p{L}\\p{N}]+[\\r\\n]*|\\s*[\\r\\n]+|\\s+(?!\\S)|\\s+`
    - I don't understand what the second one does:
    ```
          {
        "type": "ByteLevel",
        "add_prefix_space": false,
        "trim_offsets": true,
        "use_regex": false
      }
    ```
- There's about 260 new special tokens in `tokenizer.json`, but only 2 of them are defined `special_tokens_map.json` (bos and eos). It's unclear to me how the remaining 258 are supposed to be used. 255 of them are reminiscent of the old byte level tokens, but I can't find any reference that is supposed to make them behave like byte level tokens, so it's unclear to me if these are used as byte level fallback or if these are completely unused, or if these are used for some other purpose I'm unaware of. I was thinking maybe that second pretokenizer that says "type: ByteLevel", maybe that is supposed to somehow link to these special tokens, but I can't find anythink that links it to them.
- I don't understand how unknown tokens are handled. Previously they were handled with `byte_fallback` set to `true` in `tokenizer.json` , but now it's set to `false`. Also, previously `unk_token` was set but now it's no longer set (not sure why that one was set in the first place, since the byte level fallback existed there was no need for the unk token, but now that the byte level fallback is set to false, I would have imagined that there would be a need for the unknown token). In addition, the token list no longer contains any token representing the unknown token.

**Comment by CiaoHe** [comment]
I'm sorry that I'm completely stuck in the textbook stage about tokenizer, so I will try my best to check the relevant code to give some of my opinions.
Pres:
1. Llama-2 [tokenizer.json ](https://huggingface.co/NousResearch/Llama-2-7b-chat-hf/raw/main/tokenizer.json) seems has no pre-tokenizer. `post_processor` uses [TemplateProcessing](https://huggingface.co/docs/tokenizers/api/post-processors#tokenizers.processors.TemplateProcessing) 
<details>
<summary>Llama-2 tokenizer.json `pre_tokenizer` and `post_processor` part</summary>

```json
"pre_tokenizer": null,
"post_processor": {
  "type": "TemplateProcessing",
  "single": [
    {
      "SpecialToken": {
        "id": "<s>",
        "type_id": 0
      }
    },
    {
      "Sequence": {
        "id": "A",
        "type_id": 0
      }
    }
  ],
  "pair": [
    {
      "SpecialToken": {
        "id": "<s>",
        "type_id": 0
      }
    },
    {
      "Sequence": {
        "id": "A",
        "type_id": 0
      }
    },
    {
      "SpecialToken": {
        "id": "<s>",
        "type_id": 1
      }
    },
    {
      "Sequence": {
        "id": "B",
        "type_id": 1
      }
    }
  ],
  "special_tokens": {
    "<s>": {
      "id": "<s>",
      "ids": [
        1
      ],
      "tokens": [
        "<s>"
      ]
    }
  }
},
"decoder": {
  "type": "Sequence",
  "decoders": [
    {
      "type": "Replace",
      "pattern": {
        "String": "▁"
      },
      "content": " "
    },
    {
      "type": "ByteFallback"
    },
    {
      "type": "Fuse"
    },
    {
      "type": "Strip",
      "content": " ",
      "start": 1,
      "stop": 0
    }
  ]
},

```
</details>

2. Llama-3 has two pre-tokenizers [`Split` and `ByteLevel`] and different post_processors[`ByteLevel`]
<details>
<summary>Llama-3 tokenizer.json `pre_tokenizer` and `post_processor` part</summary>

```json
  "pre_tokenizer": {
    "type": "Sequence",
    "pretokenizers": [
      {
        "type": "Split",
        "pattern": {
          "Regex": "(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\\r\\n\\p{L}\\p{N}]?\\p{L}+|\\p{N}{1,3}| ?[^\\s\\p{L}\\p{N}]+[\\r\\n]*|\\s*[\\r\\n]+|\\s+(?!\\S)|\\s+"
        },
        "behavior": "Isolated",
        "invert": false
      },
      {
        "type": "ByteLevel",
        "add_prefix_space": false,
        "trim_offsets": true,
        "use_regex": false
      }
    ]
  },
  "post_processor": {
    "type": "ByteLevel",
    "add_prefix_space": true,
    "trim_offsets": false,
    "use_regex": true
  },
  "decoder": {
    "type": "ByteLevel",
    "add_prefix_space": true,
    "trim_offsets": true,
    "use_regex": true
  }
```
</details>

Others:
1. `add_prefix_space`: (bool, optional, in the ByteLevel type it defaults to True) — Whether to add a space to the first word if there isn’t already one. 
2. The basic pipeline used in hf.tokenizers encode should be (at least I guess): `Normalizer` -> `pre_tokenizer` -> `Model` (BPE etc.) -> `PostProcessor`, you can check the docs in [pipeline](https://huggingface.co/docs/tokenizers/pipeline). Finally, when decoding, they call `decoder`.

**Comment by belladoreai** [comment]
I was looking at the tokenizer files in the official Huggingface repo earlier. Now I've started going through the [tokenizer.py in the official GitHub repo](https://github.com/meta-llama/llama3/blob/main/llama/tokenizer.py) and it seems much easier to understand.

**Comment by CiaoHe** [comment]
> I was looking at the tokenizer files in the official Huggingface repo earlier. Now I've started going through the [tokenizer.py in the official GitHub repo](https://github.com/meta-llama/llama3/blob/main/llama/tokenizer.py) and it seems much easier to understand.

right, huggingface tokenizer package seems more complicated.

**Comment by belladoreai** [comment]
I can't seem to understand the Regex string `(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\\r\\n\\p{L}\\p{N}]?\\p{L}+|\\p{N}{1,3}| ?[^\\s\\p{L}\\p{N}]+` that is used to split the input in the pretokenizer. This is not a normal regex. It doesn't compile in JavaScript, Python, or Rust.

I looked at how they're using it:

1. The `tokenizer.py` file in the GitHub repo is passing the Regex string to tiktoken when the tokenizer is being initialized, here: https://github.com/meta-llama/llama3/blob/main/llama/tokenizer.py#L80
2. Tiktoken is passing it to `_tiktoken.CoreBPE` here: https://github.com/openai/tiktoken/blob/main/tiktoken/core.py#L50C36-L50C43
3. The core appears to be written in Rust, and the Regex string is handled here: https://github.com/openai/tiktoken/blob/main/src/lib.rs#L413-L460

I'm not familiar with Rust at all. I tried using some Rust online playground and I can't get the Regex string to compile.

Edit: I started looking at transformers.js (which doesn't have LLaMA 3 support yet), and it seems like transformers.js already has fixes for similar regex split issues: https://github.com/xenova/transformers.js/blob/main/src/tokenizers.js#L110-L121

```
        // In certain cases, the pattern may contain unnecessary escape sequences (e.g., \# or \& or \~).
        // i.e., valid in Python (where the patterns are exported from) but invalid in JavaScript (where the patterns are parsed).
        // This isn't an issue when creating the regex w/o the 'u' flag, but it is when the 'u' flag is used.
        // For this reason, it is necessary to remove these backslashes before creating the regex.
        // See https://stackoverflow.com/a/63007777/13989043 for more information
        let regex = pattern.Regex.replace(/\\([#&~])/g, '$1'); // TODO: add more characters to this list if necessary
```

**Comment by belladoreai** [comment]
I managed to implement the LLaMA 3 pretokenizers now by using transformers.js as a reference (basically copying a bunch of helper functions to clean up the regex etc.)

Updated tests and it seems to be working? woop woop!

PR here with more details of changes: https://github.com/belladoreai/llama3-tokenizer-js/pull/1

New repo for LLaMA 3 here: https://github.com/belladoreai/llama3-tokenizer-js

**Comment by CiaoHe** [comment]
awesome!

**Comment by belladoreai** [comment]
Please let me know if you find any issues. There was a lot of changes so I wouldn't be surprised if I broke something.
